name: xolmis
description: "Collect ornithological data in the field."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+99

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  intl: ^0.20.2
  intl_utils: ^2.8.12

  # UI dependencies
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^19.5.0
  side_sheet: ^1.0.4+1
  fab_m3e: ^0.1.1
  m3e_design: ^0.2.1
  settings_ui: ^2.0.2
  fleather: ^1.26.0
  fl_chart: ^1.1.1
  numberpicker: ^2.1.2
  image_picker: ^1.2.1
  file_picker: ^10.3.6
  share_plus: ^12.0.1
  about: ^2.2.0
#  timelines_plus: ^1.0.6

  # Data and persistence dependencies
  sqflite: ^2.4.2
  csv: ^6.0.0
  shared_preferences: ^2.5.3
  excel: ^4.0.6
  geoxml: ^2.6.2
  archive: ^3.6.1

  # State management
  provider: ^6.1.5+1
  
  # Other dependencies
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1  
  geolocator: ^14.0.2
  package_info_plus: ^8.3.1
#  workmanager: ^0.9.0+3
#    git:
#      url: https://github.com/fluttercommunity/flutter_workmanager.git
#      path: workmanager
#      ref: main
  device_info_plus: ^12.2.0
  url_launcher: ^6.3.2
#  equations: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

#dependency_overrides:
#  vector_math: 2.2.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
  assets:
    - assets/license.txt
    - assets/species_data.json
    - assets/checklists/species_data_AR.json
    - assets/checklists/species_data_BR.json
    - assets/checklists/species_data_PY.json
    - assets/checklists/species_data_UY.json
    - assets/xolmis_icon.png
    - assets/xolmis_icon_monochrome.png
    - assets/alianza_del_pastizal_logo.png
    - assets/changelog.md
    - assets/changelog-pt.md
    - assets/license.md
    - assets/updates/species_update_2025.json


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/xolmis_icon.png"
  image_path_ios: "assets/xolmis_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/xolmis_icon.png"
  adaptive_icon_foreground_inset: 16
  adaptive_icon_monochrome: "assets/xolmis_icon_monochrome.png"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter_intl:
  enabled: true
